INSERT INTO PERSONAGEM(NOME, IDADE, CLASSE) VALUES ('TESTE01',24,'GUERREIRO')
INSERT INTO PERSONAGEM(NOME, IDADE, CLASSE) VALUES ('TESTE02',20,'MAGO')
INSERT INTO PERSONAGEM(NOME, IDADE, CLASSE) VALUES ('TESTE03',19,'ARQUEIRO')